name: emotioncare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # Music
  just_audio: ^0.9.41
  audio_session: ^0.1.7

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

  # State management
  flutter_riverpod: ^2.5.1

  # UI & Tools
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  share_plus: ^10.0.0
  intl: ^0.19.0
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2

  # ğŸŒ™ AI iÃ§in gerekli
  http: ^1.2.0          # AI API Ã§aÄŸrÄ±larÄ± iÃ§in
  flutter_dotenv: ^5.1.0  # API key saklamak iÃ§in (opsiyonel ama Ã¶nerilir)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - .env.example
    - assets/music/piano.mp3
    - assets/music/focus.mp3
    - assets/music/meditation.mp3
    - assets/music/ambient.mp3
    - assets/music/sleep.mp3
    - assets/music/relaxing.mp3
